openapi: 3.0.0
info:
  title: Indian Dishes API
  version: 1.0.0

paths:
  /dishes:
    get:
      summary: Get all dishes with optional filters
      parameters:
        - in: query
          name: diet
          schema:
            type: string
        - in: query
          name: flavor
          schema:
            type: string
        - in: query
          name: state
          schema:
            type: string
        - in: query
          name: sort
          schema:
            type: string
            enum: [name, prep_time, cook_time]
        - in: query
          name: order
          schema:
            type: string
            enum: [asc, desc]
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
      responses:
        '200':
          description: List of dishes
        '500':
          description: Internal Server Error

  /dishes/{id}:
    get:
      summary: Get dish by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Dish object
        '404':
          description: Dish not found
        '500':
          description: Internal Server Error

  /suggest:
    post:
      summary: Suggest dishes by ingredients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ingredients:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: List of matching dishes
        '404':
          description: No matching dishes found
        '500':
          description: Internal Server Error

  /ingredients:
    get:
      summary: Get all unique ingredients
      responses:
        '200':
          description: List of ingredients
        '500':
          description: Internal Server Error

  /search:
    get:
      summary: Search dishes by keyword
      parameters:
        - in: query
          name: q
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of matching dishes
        '404':
          description: No dishes matched your search
        '500':
          description: Internal Server Error

  /login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: JWT token and user object
        '401':
          description: Invalid email or password
        '500':
          description: Internal Server Error

  /register:
    post:
      summary: User registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '201':
          description: Registered successfully
        '409':
          description: User already exists
        '500':
          description: Internal Server Error

  /addDish:
    post:
      tags:
        - User Specific
      summary: Add a new dish (authenticated)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dishData:
                  type: object
                  required:
                    - name
                    - ingredients
                    - diet
                  properties:
                    name:
                      type: string
                      example: Paneer Butter Masala
                    ingredients:
                      type: string
                      example: Paneer, Tomato, Butter, Spices
                    diet:
                      type: string
                      example: vegetarian
                    prep_time:
                      type: integer
                      example: 15
                    cook_time:
                      type: integer
                      example: 25
                    flavor_profile:
                      type: string
                      example: Spicy
                    course:
                      type: string
                      example: Main Course
                    state:
                      type: string
                      example: Punjab
                    region:
                      type: string
                      example: North
      responses:
        '201':
          description: Dish added successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '409':
          description: Conflict
        '500':
          description: Server error

  /my-dishes:
    get:
      tags:
        - User Specific
      summary: Get dishes created by logged-in user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of user's dishes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Modak
                    ingredients:
                      type: string
                      example: Rice flour, coconut, jaggery
                    diet:
                      type: string
                      example: vegetarian
                    user_id:
                      type: integer
                      example: 3
        '401':
          description: Unauthorized
        '500':
          description: Server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
